name: Big World of a Small Town
favicon: null
layout_spectrum: 0.98607
typography_spectrum: 0.42642161226831377
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9e1a2f'
    - '#687274'
    - '#e8bbc3'
    - '#28363f'
  brandStrength: 0.2724710190668702
  lightness: 0.2688357459846884
  saturation: 0.5625
  rhythmicContrast: 0.22352723008953035
purpose: []
